export const REQUEST_INTEREST_GROUPS = 'REQUEST_INTEREST_GROUPS';
export const RECEIVE_INTEREST_GROUPS = 'RECEIVE_INTEREST_GROUPS';

export const REQUEST_INTERESTS = 'REQUEST_INTERESTS';
export const RECEIVE_INTERESTS = 'RECEIVE_INTERESTS';
